package INTERFACES;

import java.awt.ComponentOrientation;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

public class Panel extends javax.swing.JFrame implements Runnable{

    String hora, minutos, segundos, ampm;
    Calendar cal = Calendar.getInstance();
    Calendar calendario;
    Thread h1;
    String fecha = cal.get(cal.DATE) + "/" + (cal.get(cal.MONTH) + 1) + "/" + cal.get(cal.YEAR);
    
    public void calcula() {

        calendario = new GregorianCalendar();
        Date fechaHoraActual = new Date();

        calendario.setTime(fechaHoraActual);
        ampm = calendario.get(Calendar.AM_PM) == Calendar.AM ? "AM" : "PM";

        if (ampm.equals("PM")) {
            int h = calendario.get(Calendar.HOUR_OF_DAY) - 12;
            hora = h > 9 ? "" + h : "0" + h;
        } else {
            hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        }

        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }

    public void run() {

        Thread ct = Thread.currentThread();

        while (ct == h1) {

            calcula();
            lbFecha.setText("FECHA: " + fecha);
            lbHora.setText("HORA: " + hora + ":" + minutos + ":" + segundos + " " + ampm);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }
    
    public Panel() {
        initComponents();
        //this.setSize( (int) pantalla.getWidth(), (int) pantalla.getHeight());
        //this.setLocation( (int) pantalla.getWidth() - getWidth(), 0 );
        //this.setResizable(false);
        //this.setExtendedState(MAXIMIZED_BOTH);
        h1 = new Thread(this);
        h1.start();
        menuSalir.setComponentOrientation(ComponentOrientation.UNKNOWN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbHora = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        lbWelcome = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();
        lbLogoJDM = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAlumnos = new javax.swing.JMenu();
        miNewAlumno = new javax.swing.JMenuItem();
        miListAlumnos = new javax.swing.JMenuItem();
        menuCursos = new javax.swing.JMenu();
        miNewCurso = new javax.swing.JMenuItem();
        miListCursos = new javax.swing.JMenuItem();
        menuDocentes = new javax.swing.JMenu();
        miNewDocente = new javax.swing.JMenuItem();
        miListDocentes = new javax.swing.JMenuItem();
        menuMatriculas = new javax.swing.JMenu();
        miNewMatricula = new javax.swing.JMenuItem();
        miListMatriculas = new javax.swing.JMenuItem();
        menuNotas = new javax.swing.JMenu();
        miNewNota = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuKardex = new javax.swing.JMenu();
        miNewKardex = new javax.swing.JMenuItem();
        miListKardex = new javax.swing.JMenuItem();
        menuTramites = new javax.swing.JMenu();
        miNewTramite = new javax.swing.JMenuItem();
        miListTramites = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        miNewUser = new javax.swing.JMenuItem();
        miListUsers = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(22, 45, 80));
        setSize(new java.awt.Dimension(900, 503));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbHora.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lbHora.setForeground(new java.awt.Color(255, 238, 170));
        getContentPane().add(lbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, 200, 50));

        lbFecha.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lbFecha.setForeground(new java.awt.Color(255, 238, 170));
        getContentPane().add(lbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 200, 50));

        lbWelcome.setBackground(new java.awt.Color(22, 45, 80));
        lbWelcome.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        lbWelcome.setForeground(new java.awt.Color(160, 44, 44));
        lbWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWelcome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbWelcome.setMaximumSize(new java.awt.Dimension(129, 40));
        lbWelcome.setMinimumSize(new java.awt.Dimension(129, 40));
        lbWelcome.setOpaque(true);
        lbWelcome.setPreferredSize(new java.awt.Dimension(129, 40));
        getContentPane().add(lbWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 140));

        lbLogo.setBackground(new java.awt.Color(22, 45, 80));
        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/LOGO-SITRADOC.PNG"))); // NOI18N
        lbLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbLogo.setOpaque(true);
        getContentPane().add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 900, 190));

        lbLogoJDM.setBackground(new java.awt.Color(22, 45, 80));
        lbLogoJDM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/LOGOJDM.png"))); // NOI18N
        lbLogoJDM.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbLogoJDM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbLogoJDM.setOpaque(true);
        getContentPane().add(lbLogoJDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 900, 150));

        jMenuBar1.setBackground(new java.awt.Color(255, 238, 170));

        menuAlumnos.setBackground(new java.awt.Color(255, 238, 170));
        menuAlumnos.setForeground(new java.awt.Color(22, 45, 80));
        menuAlumnos.setText("ALUMNOS");

        miNewAlumno.setBackground(new java.awt.Color(255, 238, 170));
        miNewAlumno.setForeground(new java.awt.Color(22, 45, 80));
        miNewAlumno.setText("AGREGAR");
        menuAlumnos.add(miNewAlumno);

        miListAlumnos.setBackground(new java.awt.Color(255, 238, 170));
        miListAlumnos.setForeground(new java.awt.Color(22, 45, 80));
        miListAlumnos.setText("LISTA");
        menuAlumnos.add(miListAlumnos);

        jMenuBar1.add(menuAlumnos);

        menuCursos.setBackground(new java.awt.Color(255, 238, 170));
        menuCursos.setForeground(new java.awt.Color(22, 45, 80));
        menuCursos.setText("CURSOS");

        miNewCurso.setBackground(new java.awt.Color(255, 238, 170));
        miNewCurso.setForeground(new java.awt.Color(22, 45, 80));
        miNewCurso.setText("AGREGAR");
        menuCursos.add(miNewCurso);

        miListCursos.setBackground(new java.awt.Color(255, 238, 170));
        miListCursos.setForeground(new java.awt.Color(22, 45, 80));
        miListCursos.setText("LISTA");
        menuCursos.add(miListCursos);

        jMenuBar1.add(menuCursos);

        menuDocentes.setBackground(new java.awt.Color(255, 238, 170));
        menuDocentes.setForeground(new java.awt.Color(22, 45, 80));
        menuDocentes.setText("DOCENTES");

        miNewDocente.setBackground(new java.awt.Color(255, 238, 170));
        miNewDocente.setForeground(new java.awt.Color(22, 45, 80));
        miNewDocente.setText("AGREGAR");
        menuDocentes.add(miNewDocente);

        miListDocentes.setBackground(new java.awt.Color(255, 238, 170));
        miListDocentes.setForeground(new java.awt.Color(22, 45, 80));
        miListDocentes.setText("LISTA");
        menuDocentes.add(miListDocentes);

        jMenuBar1.add(menuDocentes);

        menuMatriculas.setBackground(new java.awt.Color(255, 238, 170));
        menuMatriculas.setForeground(new java.awt.Color(22, 45, 80));
        menuMatriculas.setText("MATRÍCULAS");

        miNewMatricula.setBackground(new java.awt.Color(255, 238, 170));
        miNewMatricula.setForeground(new java.awt.Color(22, 45, 80));
        miNewMatricula.setText("REGISTRAR");
        menuMatriculas.add(miNewMatricula);

        miListMatriculas.setBackground(new java.awt.Color(255, 238, 170));
        miListMatriculas.setForeground(new java.awt.Color(22, 45, 80));
        miListMatriculas.setText("BUSCAR");
        menuMatriculas.add(miListMatriculas);

        jMenuBar1.add(menuMatriculas);

        menuNotas.setBackground(new java.awt.Color(255, 238, 170));
        menuNotas.setForeground(new java.awt.Color(22, 45, 80));
        menuNotas.setText("NOTAS");

        miNewNota.setBackground(new java.awt.Color(255, 238, 170));
        miNewNota.setForeground(new java.awt.Color(22, 45, 80));
        miNewNota.setText("REGISTRAR");
        menuNotas.add(miNewNota);

        jSeparator1.setForeground(new java.awt.Color(22, 45, 80));
        menuNotas.add(jSeparator1);

        menuKardex.setBackground(new java.awt.Color(255, 238, 170));
        menuKardex.setForeground(new java.awt.Color(22, 45, 80));
        menuKardex.setText("KARDEX");
        menuKardex.setFocusable(false);

        miNewKardex.setBackground(new java.awt.Color(255, 238, 170));
        miNewKardex.setForeground(new java.awt.Color(22, 45, 80));
        miNewKardex.setText("GENERAR");
        menuKardex.add(miNewKardex);

        miListKardex.setBackground(new java.awt.Color(255, 238, 170));
        miListKardex.setForeground(new java.awt.Color(22, 45, 80));
        miListKardex.setText("BUSCAR");
        miListKardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListKardexActionPerformed(evt);
            }
        });
        menuKardex.add(miListKardex);

        menuNotas.add(menuKardex);

        jMenuBar1.add(menuNotas);

        menuTramites.setBackground(new java.awt.Color(255, 238, 170));
        menuTramites.setForeground(new java.awt.Color(22, 45, 80));
        menuTramites.setText("TRÁMITES");

        miNewTramite.setBackground(new java.awt.Color(255, 238, 170));
        miNewTramite.setForeground(new java.awt.Color(22, 45, 80));
        miNewTramite.setText("NUEVO");
        menuTramites.add(miNewTramite);

        miListTramites.setBackground(new java.awt.Color(255, 238, 170));
        miListTramites.setForeground(new java.awt.Color(22, 45, 80));
        miListTramites.setText("LISTA");
        miListTramites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListTramitesActionPerformed(evt);
            }
        });
        menuTramites.add(miListTramites);

        jMenuBar1.add(menuTramites);

        menuUsuarios.setBackground(new java.awt.Color(255, 238, 170));
        menuUsuarios.setForeground(new java.awt.Color(22, 45, 80));
        menuUsuarios.setText("USUARIOS");
        menuUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        miNewUser.setBackground(new java.awt.Color(255, 238, 170));
        miNewUser.setForeground(new java.awt.Color(22, 45, 80));
        miNewUser.setText("AGREGAR");
        menuUsuarios.add(miNewUser);

        miListUsers.setBackground(new java.awt.Color(255, 238, 170));
        miListUsers.setForeground(new java.awt.Color(22, 45, 80));
        miListUsers.setText("LISTA");
        menuUsuarios.add(miListUsers);

        jMenuBar1.add(menuUsuarios);

        menuSalir.setBackground(new java.awt.Color(255, 238, 170));
        menuSalir.setForeground(new java.awt.Color(160, 44, 44));
        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/log-out.png"))); // NOI18N
        menuSalir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        menuSalir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miListKardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListKardexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miListKardexActionPerformed

    private void miListTramitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListTramitesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miListTramitesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbLogoJDM;
    private javax.swing.JLabel lbWelcome;
    private javax.swing.JMenu menuAlumnos;
    private javax.swing.JMenu menuCursos;
    private javax.swing.JMenu menuDocentes;
    private javax.swing.JMenu menuKardex;
    private javax.swing.JMenu menuMatriculas;
    private javax.swing.JMenu menuNotas;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenu menuTramites;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JMenuItem miListAlumnos;
    private javax.swing.JMenuItem miListCursos;
    private javax.swing.JMenuItem miListDocentes;
    private javax.swing.JMenuItem miListKardex;
    private javax.swing.JMenuItem miListMatriculas;
    private javax.swing.JMenuItem miListTramites;
    private javax.swing.JMenuItem miListUsers;
    private javax.swing.JMenuItem miNewAlumno;
    private javax.swing.JMenuItem miNewCurso;
    private javax.swing.JMenuItem miNewDocente;
    private javax.swing.JMenuItem miNewKardex;
    private javax.swing.JMenuItem miNewMatricula;
    private javax.swing.JMenuItem miNewNota;
    private javax.swing.JMenuItem miNewTramite;
    private javax.swing.JMenuItem miNewUser;
    // End of variables declaration//GEN-END:variables
}
